# permissions for end users to edit capacities.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capacity-editor-role
rules:
- apiGroups:
  - kueue.x-k8s.io
  resources:
  - capacities
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kueue.x-k8s.io
  resources:
  - capacities/status
  verbs:
  - get
