# permissions for end users to view queuedworkloads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: queuedworkload-viewer-role
rules:
- apiGroups:
  - kueue.gke-internal.googlesource.com
  resources:
  - queuedworkloads
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kueue.gke-internal.googlesource.com
  resources:
  - queuedworkloads/status
  verbs:
  - get
