# permissions for end users to edit queuedworkloads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: queuedworkload-editor-role
rules:
- apiGroups:
  - kueue.gke-internal.googlesource.com
  resources:
  - queuedworkloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kueue.gke-internal.googlesource.com
  resources:
  - queuedworkloads/status
  verbs:
  - get
