# permissions for end users to view queuedworkloads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: queuedworkload-viewer-role
  labels:
    rbac.kueue.x-k8s.io/batch-admin: "true"
    rbac.kueue.x-k8s.io/batch-user: "true"
rules:
- apiGroups:
  - kueue.x-k8s.io
  resources:
  - queuedworkloads
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kueue.x-k8s.io
  resources:
  - queuedworkloads/status
  verbs:
  - get
