# permissions for end users to edit queues.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: queue-editor-role
rules:
- apiGroups:
  - kueue.gke-internal.googlesource.com
  resources:
  - queues
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kueue.gke-internal.googlesource.com
  resources:
  - queues/status
  verbs:
  - get
