# This workflow runs the make sync-hugo-version command and alters the dependabot pr
# Test comment to see if this triggers the action
name: Hugo Version Synchronizer

on:
  pull_request_target:
    branches: [ main ]

jobs:
    add-approve-lgtm-label:
        #if: ${{ github.actor == 'dependabot[bot]' && contains(github.event.pull_request.labels.*.name, 'dependabot') }}
        runs-on: ubuntu-latest

        # Permission required to edit a PR
        permissions:
          pull-requests: write
          issues: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Run make sync-hugo-version
              run: |
                  make sync-hugo-version
            - name: Commit commit changes
              run: |
                  add netlify.toml
                  commit -m "Bump Hugo Version in netlify.toml"
              env:
                GITHUB_TOKEN: ${{ secrets.GH_CLI_TOKEN }}
