# This workflow runs the make sync-hugo-version command and alters the dependabot pr
# Test comment to see if this triggers the action
# Test comment 2 to see if the new change is successfully commited after running
# Test commenmt 3 to see if the new change is succesful
name: Hugo Version Synchronizer

on:
  pull_request_target:
    branches: [ main ]

jobs:
    run-sync-hugo-version:
        #if: ${{ github.actor == 'dependabot[bot]' && contains(github.event.pull_request.labels.*.name, 'dependabot') }}
        runs-on: ubuntu-latest

        # Permission required to edit a PR
        permissions:
          pull-requests: write
          issues: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Run make sync-hugo-version
              run: |
                  make sync-hugo-version
            - name: Commit changes
              uses: devops-infra/action-commit-push@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  commit_message: Run make sync-hugo-version
